#!/usr/bin/env python3
# my comment

from pymongo import MongoClient


def list_databases():
    """
    List all databases in MongoDB.
    """
    # Connect to MongoDB server
    client = MongoClient('mongodb://127.0.0.1:27017')

    # Get the list of databases
    databases = client.list_database_names()

    # Print each database name
    for db in databases:
        print(db)


if __name__ == "__main__":
    list_databases()
